apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cheers
  name: cheers
spec:
  containers:
  - env:
    - name: EXO_4
      value: '1'
    - name: KUBE_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    image: kanedafromparis/cheers:0.0.2
    imagePullPolicy: IfNotPresent
    name: cheers
    ports:
    - containerPort: 8080
      protocol: TCP
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  securityContext: {}
  terminationGracePeriodSeconds: 30
