apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cheers
  name: cheers
spec:
  containers:
  - image: kanedafromparis/cheers:0.0.2
    imagePullPolicy: IfNotPresent
    name: cheers
    ports:
    - containerPort: 8080
      protocol: TCP
