apiVersion: v1
kind: Pod
metadata:
  name: nginx-001
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-002
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 8080
      protocol: TCP

--
apiVersion: v1
kind: Pod
metadata:
  name: nginx-001
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 8080
      protocol: TCP
