apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fortune
  name: fortune
spec:
  containers:
  - env:
    - name: VERBOSE
      value: ''
# Ajouter l'URL de votre image 
    image: 
    imagePullPolicy: IfNotPresent
    name: fortune
