apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fortune
  name: fortune
spec:
  containers:
  - env:
    - name: VERBOSE
      value: '0'
# Ajouter l'URL de votre image 
    image: kanedafromparis/fortune:ocp-0.1
    imagePullPolicy: IfNotPresent
    name: fortune
    volumeMounts:
    - mountPath: /opt/exchange
      name: exchange
# Le deuxieme conenteur 
  - env:
    - name: VERBOSE
      value: '1'
    args:
    - /run-tail.sh
    image: kanedafromparis/fortune:ocp-0.1
    imagePullPolicy: IfNotPresent
    name: tail
    volumeMounts:
    - mountPath: /opt/exchange
      name: exchange
  terminationGracePeriodSeconds: 1
# Le volume 'exchange' defini dans le POD
  volumes:
  - name: exchange
    emptyDir: {}