apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fortune
  name: fortune
spec:
  containers:
  - env:
    - name: VERBOSE
      value: '0'
    args:
    - /run-fortune.sh
    image: kanedafromparis/fortune:ocp-0.1
    imagePullPolicy: IfNotPresent
    name: fortune
    volumeMounts:
    - mountPath: /opt/exchange
      name: exchange
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
### Deuxieme conteneur
  - args:
    - /run-tail.sh
    image: kanedafromparis/fortune:ocp-0.1
    imagePullPolicy: IfNotPresent
    name: tail
    volumeMounts:
    - mountPath: /opt/exchange
      name: exchange
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 1
  volumes:
  - name: exchange
    emptyDir: {}