apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    kaneda-k.net/exo: exo0100
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /data/pv0001/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  labels:
    kaneda-k.net/exo: exo0100
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /data/pv0002/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    kaneda-k.net/exo: exo0100
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /data/pv0003/