apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: logsversion
  name: logsversion
spec:
  replicas: 2
  selector:
    matchLabels:
      run: logsversion
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: logsversion
    spec:
      containers:
      - image: kanedafromparis/logversion:1.0
        imagePullPolicy: IfNotPresent
        name: logsversion
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5