apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: rsm
  name: rsm
spec:
  progressDeadlineSeconds: 10
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      run: rsm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rsm
    spec:
      containers:
      - env:
        - name: SLOW_LIVENESS
          value: "500"
        - name: SLOW_READINESS
          value: "500"
        image: kanedafromparis/resourcesmonger:1.2
        imagePullPolicy: IfNotPresent
        name: rsm
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30        
      

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: rsm
  name: rsm
spec:
  ports:
  - nodePort: 30877
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: rsm
  sessionAffinity: None
  type: NodePort      
    